on:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Netlify deploy preview
      uses: jakejarvis/lighthouse-action@master
      with:
        netlify_site: 'pedantic-brahmagupta-25f079.netlify.com/'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: HTML Code Check
      uses: chabad360/htmlproofer@master
      with:
          directory: "./"
          # The directory to scan
          arguments: --check-favicon --check-img-http --enforce-https --disable-external --alt-ignore https://www.facebook.com/tr?id=154907775729568&ev=PageView&noscript=1
          # The arguments to pass to HTMLProofer
