on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: HTML Code Check
      uses: chabad360/htmlproofer@master
      with:
          directory: "./"
          # The directory to scan
          arguments: --check-favicon --check-img-http --enforce-https --disable-external --url-ignore facebook.com
          # The arguments to pass to HTMLProofer
